export const navlinks = [
  { href: "/", text: "home" },
  { href: "/work", text: "work" },
  {
    text: "Services",
    href: "/services",
    sublinks: [
      {
        text: "Build & Design Solutions",
        href: "/services/build-design-solutions",
      },
      {
        text: "Site Viability Analysis",
        href: "/services/site-viability-analysis",
      },
      {
        text: "Design-to-Delivery Architecture",
        href: "/services/design-to-delivery-architecture",
      },
      {
        text: "Interior Fit-Out Expertise",
        href: "/services/interior-fit-outexpertise",
      },
      {
        text: "Complete Interior Solutions",
        href: "/services/complete-nterior-solutions",
      },
      {
        text: "Landscape Excellence Services",
        href: "/services/landscape-excellence-services",
      },
      {
        text: "3D Modeling & Drawing Services",
        href: "/services/3d-modeling-rawing-services",
      },
    ],
  },
  { href: "/about_us", text: "about us" },

  //{href:"/contactus" ,text:"contact us"}
];

export const banners = [
  {
    id: "c1",
    title: "Architecture",
    description: "Winter has so much to offer - creative activities",
    image: "/images/img1.jpg", // Update with your actual image path
  },
  {
    id: "c2",
    title: "Interior Designing",
    description: "Gets better every day - stay tuned",
    image: "/images/img2.jpg",
  },
  {
    id: "c3",
    title: "Civil Contracts",
    description: "Help people all over the world",
    image: "/images/img3.jpg",
  },
  {
    id: "c4",
    title: "Project management consultant",
    description: "Space engineering becomes more advanced",
    image: "/images/img4.jpg",
  },
];

export const cardsData = [
  {
    id: "c1",
    title: "Architecture",
    description:
      "Transforming spaces into iconic structures with innovative designs and sustainable solutions.",
    image: "/images/img1.jpg", // Update with your actual image path
  },
  {
    id: "c2",
    title: "Interior Designing",
    description:
      "Crafting elegant and functional interiors that reflect your personality and enhance your lifestyle.",
    image: "/images/img2.jpg",
  },
  {
    id: "c3",
    title: "Civil Contracts",
    description:
      "Delivering reliable civil engineering solutions to bring your vision to life with precision and efficiency.",
    image: "/images/img3.jpg",
  },
  {
    id: "c4",
    title: "Project management consultant",
    description:
      "Ensuring seamless project execution with expert planning, coordination, and management services.",
    image: "/images/img4.jpg",
  },
];

export const homework = [
  {
    slug: "project_name",
    title: "Project name",
    description: "this is the description of the product",
    image: "/images/img4.jpg",
  },
];

export interface Project {
  id: number;
  title: string;
  slug: string;
  image: string;
  category:
    | "Commercial"
    | "Hotel"
    | "Institutes"
    | "Residential"
    | "Interior design";
  aspectRatio: string;
  description: string;
  shortDescription: string;
  year?: number;
  client?: string;
  location: string;
  area?: string;
  builtarea?: string;
  services?: string[];
  team?: string[];
  awards?: string[];
  gallery?: string[];
  challenge?: string;
  solution?: string;
  status: "Completed" | "In Progress" | "Planning Phase" | "Unbuilt";
  sustainability?: string[];
  technologies?: string[];
}

export const projects: Project[] = [
  {
    id: 1,
    title: "ABIIL Boulevard",
    slug: "ABIIL-Boulevard",
    image: "/images/Project_1/abil_boulvard.jpg",
    category: "Commercial",
    aspectRatio: "4/3",
    description:
      "A state-of-the-art commercial complex featuring modern architecture and sustainable design principles. The project seamlessly integrates work and leisure spaces, creating a dynamic environment for businesses and their employees.",
    shortDescription:
      "Modern commercial complex with sustainable design features",
    year: 2024,
    client: "ABIL Propcon LLP",
    location: "Ghorpadi, Pune",
    area: "9400 sq ft",
    builtarea: "42,302 sq ft",
    services: ["Architectural Design"],
    team: [
      "Kaustubh Shevade",
      "Amit Chaubal",
      "Ramachandra Sadavatti",
      "Laxman Gundu",
    ],
    gallery: [
      "/images/Project_1/abil_boulvard.jpg",
      "/images/Project_1/abil_boulvard1.jpg",
      "/images/Project_1/abil_boulvard2.jpg",
    ],
    challenge:
      "Creating a sustainable commercial space that maximizes natural light while maintaining energy efficiency.",
    solution:
      "Implemented a double-skin facade system and smart building technologies.",
    status: "Completed",
  },
  {
    id: 2,
    title: "Science Research Centre, IIT Bombay",
    slug: "Science-research-center-IITBombay",
    image: "/images/Project_2/science_research_center1.jpg",
    category: "Institutes",
    aspectRatio: "3/4",
    description:
      "A state-of-the-art commercial complex featuring modern architecture and sustainable design principles. The project seamlessly integrates work and leisure spaces, creating a dynamic environment for businesses and their employees.",
    shortDescription:
      "Modern commercial complex with sustainable design features",
    year: 2016,
    client: "IIT Bombay",
    location: "IIT Bombay,Mumbai Maharashtra",
    area: "1.95 Acre",
    builtarea: "80,000 sq m",
    services: ["Architectural Design"],
    team: ["Kaustubh Shevade", "Amit Chaubal"],
    gallery: [
      "/images/Project_2/science_research_center1.jpg",
      "/images/Project_2/science_research_center2.jpg",
      "/images/Project_2/science_research_center3.jpg",
      "/images/Project_2/science_research_center4.jpg",
      "/images/Project_2/science_research_center5.jpg",
      "/images/Project_2/science_research_center6.jpg",
    ],
    challenge:
      "Creating a sustainable commercial space that maximizes natural light while maintaining energy efficiency.",
    solution:
      "Implemented a double-skin facade system and smart building technologies.",
    status: "Unbuilt",
  },
  {
    id: 3,
    title: "Sales Tax Office Mazgaon",
    slug: "Sales-Tax-Office-Mazgaon",
    image: "/images/Project_3/taxofficemazgaon1.jpg",
    category: "Commercial",
    aspectRatio: "1/1",
    description:
      "A modern educational auditorium designed for optimal acoustics and flexible usage patterns.",
    shortDescription: "State-of-the-art educational auditorium",
    year: 2012,
    client: "Sales Tax Department",
    location: "Mazgaon, Mumbai",
    area: "1,555 sq ft",
    builtarea: "54,218 sq m",
    services: ["Architectural Design"],
    team: ["Kaustubh Shevade", "Amit Chaubal"],
    gallery: [
      "/images/Project_3/taxofficemazgaon1.jpg",
      "/images/Project_3/taxofficemazgaon2.jpg",
      "/images/Project_3/taxofficemazgaon3.jpg",
      "/images/Project_3/taxofficemazgaon4.jpg",
      "/images/Project_3/taxofficemazgaon5.jpg",
    ],
    challenge:
      "Creating perfect acoustics while maintaining flexibility for different events.",
    solution: "Implemented modular acoustic panels and advanced sound systems.",
    status: "Completed",
  },
  {
    id: 25,
    title: "Modern Minimalist Apartment",
    slug: "modern-minimalist-apartment",
    image: "/images/interior-resedential/1.jpg",
    category: "Interior design",
    aspectRatio: "4/3",
    description:
      "A sleek and modern apartment featuring a minimalist design approach with neutral tones and efficient space utilization.",
    shortDescription: "Minimalist design with a modern touch.",
    location: "Pune",
    gallery: [
      "/images/interior-resedential/1.jpg",
      "/images/interior-resedential/2.jpg",
      "/images/interior-resedential/3.jpg",
      "/images/interior-resedential/4.jpg",
      "/images/interior-resedential/5.jpg",
      "/images/interior-resedential/6.jpg",
      "/images/interior-resedential/7.jpg",
      "/images/interior-resedential/8.jpg",
      "/images/interior-resedential/9.jpg",
      "/images/interior-resedential/10.jpg",
      "/images/interior-resedential/11.jpg",
      "/images/interior-resedential/12.jpg",
      "/images/interior-resedential/13.jpg",
      "/images/interior-resedential/14.jpg",
      "/images/interior-resedential/15.jpg",
      "/images/interior-resedential/16.jpg",
    ],
    status: "Completed",
  },
  {
    id: 4,
    title: "Shopping Center",
    slug: "Shopping-Center",
    image: "/images/Project_4/shoppingcenter1.jpg",
    category: "Commercial",
    aspectRatio: "3/4",
    description:
      "An elegant hotel lobby that balances luxury with functionality, featuring smart space planning and high-end finishes.",
    shortDescription: "Luxurious hotel lobby with modern amenities",
    year: 2015,
    client: "IIT Bombay",
    location: "IIT Bombay, Maharashtra",
    area: "500 sq ft",
    builtarea: "303.50 sq m",
    services: ["Architectural Design"],
    team: ["Kaustubh Shevade", "Amit Chaubal"],
    gallery: [
      "/images/Project_4/shoppingcenter1.jpg",
      "/images/Project_4/shoppingcenter2.jpg",
      "/images/Project_4/shoppingcenter3.jpg",
      "/images/Project_4/shoppingcenter4.jpg",
    ],
    challenge:
      "Balancing luxury aesthetics with practical guest flow management.",
    solution: "Created distinct zones while maintaining visual continuity.",
    status: "Unbuilt",
  },
  {
    id: 5,
    title: "CII-Godrej GBC New Building",
    slug: "cii-godrej-gbc-new-building",
    image: "/images/Project_5/cii-godrej-gbc-new-building1.JPG",
    category: "Commercial",
    aspectRatio: "4/3",
    description:
      "A competition project for the CII-Godrej GBC new building in Hyderabad, focusing on innovative and sustainable architectural design.",
    shortDescription:
      "Sustainable architectural design for CII-Godrej GBC's new building.",
    year: 2019,
    client: "CII GBC, Hyderabad",
    location: "Hyderabad",
    area: "2,744",
    builtarea: "",
    services: ["Architecture"],
    team: ["Amit Chaubal", "Kaustubh Shevade"],
    gallery: [
      "/images/Project_5/cii-godrej-gbc-new-building1.JPG",
      "/images/Project_5/cii-godrej-gbc-new-building2.JPG",
      "/images/Project_5/cii-godrej-gbc-new-building3.JPG",
      "/images/Project_5/cii-godrej-gbc-new-building4.JPG",
      "/images/Project_5/cii-godrej-gbc-new-building5.JPG",
      "/images/Project_5/cii-godrej-gbc-new-building6.JPG",
      "/images/Project_5/cii-godrej-gbc-new-building7.JPG",
    ],
    challenge:
      "Designing a cutting-edge, sustainable building concept for the competition.",
    solution:
      "Proposed innovative green building techniques and efficient layouts.",
    status: "Unbuilt",
  },
  {
    id: 6,
    title: "One Avante",
    slug: "one-avante",
    image: "/images/Project_5/cii-godrej-gbc-new-building1.JPG",
    category: "Commercial",
    aspectRatio: "4/3",
    description:
      "A commercial architecture project for Avante Spaces Limited in Kothrud, Pune, showcasing innovative design solutions.",
    shortDescription: "Commercial project for Avante Spaces Limited in Pune.",
    year: 2024,
    client: "Avante Spaces Limited, Pune",
    location: "Kothrud, Pune",
    area: "",
    builtarea: "",
    services: ["Architecture"],
    team: ["Amit Chaubal", "Kaustubh Shevade"],
    gallery: ["/images/img6/detail1.jpg", "/images/img6/detail2.jpg"],
    challenge: "Creating a modern and functional commercial design.",
    solution:
      "Designed a contemporary space meeting the client's needs and aesthetic expectations.",
    status: "Completed",
  },{
    id: 30,
    title: "Dynamic Retail Space",
    slug: "dynamic-retail-space",
    image: "/images/interior-office/7.jpg",
    category: "Interior design",
    aspectRatio: "4/3",
    description:
      "A retail store designed to maximize customer engagement through thoughtful layouts and vibrant aesthetics.",
    shortDescription: "Vibrant and engaging retail design.",
    location: "Pune",
    gallery: [
      "/images/interior-office/1.jpg",
      "/images/interior-office/2.jpg",
      "/images/interior-office/3.jpg",
      "/images/interior-office/4.jpg",
      "/images/interior-office/5.jpg",
      "/images/interior-office/6.jpg",
      "/images/interior-office/7.jpg",
      "/images/interior-office/8.jpg",
      "/images/interior-office/9.jpg",
      "/images/interior-office/10.jpg",
      "/images/interior-office/11.jpg",
      "/images/interior-office/12.jpg",
      "/images/interior-office/13.jpg",
      "/images/interior-office/14.jpg",
      "/images/interior-office/15.jpg",
      "/images/interior-office/16.jpg",
      "/images/interior-office/17.jpg",
      "/images/interior-office/18.jpg",
      "/images/interior-office/19.jpg",
      "/images/interior-office/20.jpg",
      "/images/interior-office/21.jpg",
      "/images/interior-office/22.jpg",
      "/images/interior-office/23.jpg",
      "/images/interior-office/24.jpg",
      "/images/interior-office/25.jpg"
    ],
    status: "Completed",
  },
  {
    id: 7,
    title: "BARC, Mysore",
    slug: "barc-mysore",
    image: "/images/img7.jpg",
    category: "Commercial",
    aspectRatio: "4/3",
    description:
      "Master Plan for Technology Development Facility at BARC, Mysore, Karnataka.",
    shortDescription:
      "Master planning for a technology facility at BARC, Mysore.",
    year: 2011,
    client: "BARC, Mysore",
    location: "Karnataka",
    area: "5,706,068 sq ft",
    builtarea: "",
    services: ["Architecture"],
    team: ["Amit Chaubal", "Kaustubh Shevade"],
    gallery: ["/images/img7/detail1.jpg", "/images/img7/detail2.jpg"],
    challenge: "Designing a functional technology development facility.",
    solution:
      "Created a comprehensive master plan meeting BARC's requirements.",
    status: "In Progress",
  },
  {
    id: 8,
    title: "Master Plan For IIT Dharwad Campus",
    slug: "iit-dharwad-campus",
    image: "/images/Project_8/iit_d1.JPG",
    category: "Institutes",
    aspectRatio: "4/3",
    description:
      "Master Plan for IIT Dharwad Campus, an unbuilt competition project.",
    shortDescription:
      "Comprehensive master plan for the proposed IIT Dharwad Campus.",
    year: 2018,
    client: "IIT Dharwad",
    location: "Dharwad, Karnataka",
    area: "470.21 Acres",
    builtarea: "1,293,000 sq. m.",
    services: ["Architecture"],
    team: ["Amit Chaubal", "Kaustubh Shevade"],
    gallery: [
      "/images/Project_8/iit_d1.JPG",
      "/images/Project_8/iit_d2.JPG",
      "/images/Project_8/iit_d3.JPG",
      "/images/Project_8/iit_d4.JPG",
      "/images/Project_8/iit_d5.JPG",
      "/images/Project_8/iit_d6.JPG",
      "/images/Project_8/iit_d7.JPG",
    ],
    challenge: "Designing a futuristic educational campus for IIT Dharwad.",
    solution: "Created an innovative master plan to align with IIT’s vision.",
    status: "Unbuilt",
  },
  {
    id: 9,
    title: "Library Building For Central University of Zharkhand",
    slug: "library-building-for-central-university-of-zharkhand",
    image: "/images/img9.jpg",
    category: "Institutes",
    aspectRatio: "16/9",
    description:
      "A modern residential project that pushes the boundaries of contemporary living spaces.",
    shortDescription: "Modern family home with innovative design",
    year: 2019,
    client: "Central University of Zharkhand",
    location: "Ranchi, Zharkhand",
    area: "",
    builtarea: "",
    services: ["Architecture"],
    team: ["Amit Chaubal", "Kaustubh Shevade"],
    gallery: ["/images/img4/detail1.jpg", "/images/img4/detail2.jpg"],
    challenge:
      "Integrating modern design while maintaining warmth and livability.",
    solution:
      "Used natural materials and created flowing indoor-outdoor spaces.",
    status: "Completed",
  },{
    id: 26,
    title: "Luxury Penthouse Makeover",
    slug: "luxury-penthouse-makeover",
    image: "/images/interior-resedential/2.jpg",
    category: "Interior design",
    aspectRatio: "4/3",
    description:
      "A stunning transformation of a penthouse into a luxurious living space with bespoke furniture and premium materials.",
    shortDescription: "High-end makeover for a penthouse.",
    location: "Pune",
    gallery: [
      "/images/interior-resedential/1.jpg",
      "/images/interior-resedential/2.jpg",
      "/images/interior-resedential/3.jpg",
      "/images/interior-resedential/4.jpg",
      "/images/interior-resedential/5.jpg",
      "/images/interior-resedential/6.jpg",
      "/images/interior-resedential/7.jpg",
      "/images/interior-resedential/8.jpg",
      "/images/interior-resedential/9.jpg",
      "/images/interior-resedential/10.jpg",
      "/images/interior-resedential/11.jpg",
      "/images/interior-resedential/12.jpg",
      "/images/interior-resedential/13.jpg",
      "/images/interior-resedential/14.jpg",
      "/images/interior-resedential/15.jpg",
      "/images/interior-resedential/16.jpg",
    ],
    status: "Completed",
  },
  {
    id: 11,
    title: "Hostel blocks For Central University of Zharkhand",
    slug: "hostel-building-for-central-university-of-zharkhand",
    image: "/images/img11.jpg",
    category: "Institutes",
    aspectRatio: "16/9",
    description:
      "A modern residential project that pushes the boundaries of contemporary living spaces.",
    shortDescription: "Modern family home with innovative design",
    year: 2019,
    client: "Central University of Zharkhand",
    location: "Ranchi, Zharkhand",
    area: "",
    builtarea: "",
    services: ["Architecture"],
    team: ["Amit Chaubal", "Kaustubh Shevade"],
    gallery: ["/images/img4/detail1.jpg", "/images/img4/detail2.jpg"],
    challenge:
      "Integrating modern design while maintaining warmth and livability.",
    solution:
      "Used natural materials and created flowing indoor-outdoor spaces.",
    status: "Completed",
  },
  {
    id: 27,
    title: "Contemporary Office Design",
    slug: "contemporary-office-design",
    image: "/images/interior-office/1.jpg",
    category: "Interior design",
    aspectRatio: "4/3",
    description:
      "An innovative office design focusing on functionality, open spaces, and collaborative work areas.",
    shortDescription: "Innovative and functional office design.",
    location: "Pune",
    gallery: [
      "/images/interior-office/1.jpg",
      "/images/interior-office/2.jpg",
      "/images/interior-office/3.jpg",
      "/images/interior-office/4.jpg",
      "/images/interior-office/5.jpg",
      "/images/interior-office/6.jpg",
      "/images/interior-office/7.jpg",
      "/images/interior-office/8.jpg",
      "/images/interior-office/9.jpg",
      "/images/interior-office/10.jpg",
      "/images/interior-office/11.jpg",
      "/images/interior-office/12.jpg",
      "/images/interior-office/13.jpg",
      "/images/interior-office/14.jpg",
      "/images/interior-office/15.jpg",
      "/images/interior-office/16.jpg",
      "/images/interior-office/17.jpg",
      "/images/interior-office/18.jpg",
      "/images/interior-office/19.jpg",
      "/images/interior-office/20.jpg",
      "/images/interior-office/21.jpg",
      "/images/interior-office/22.jpg",
      "/images/interior-office/23.jpg",
      "/images/interior-office/24.jpg",
      "/images/interior-office/25.jpg"
    ],
    status: "Completed",
  },
  {
    id: 12,
    title:
      "Mastre Plan and Architecture For Shri Samarth Educational & Reserch Foundation Kolhapur",
    slug: "master-plan-and-architecture-for-shri-samarth-educational-research-foundation",
    image: "/images/Project_12/samartheducation1.jpg",
    category: "Institutes",
    aspectRatio: "1/9",
    description:
      "A modern residential project that pushes the boundaries of contemporary living spaces.",
    shortDescription: "Modern family home with innovative design",
    year: 2011,
    client: "Shri Samarth Educational & Reserch Foundation Kolhapur",
    location: "Kolhapur, Maharashtra",
    area: "52,500",
    builtarea: "21,923 sq m",
    services: ["Architecture"],
    team: ["Amit Chaubal", "Kaustubh Shevade"],
    gallery: [
      "/images/Project_12/samartheducation1.jpg",
      "/images/Project_12/samartheducation2.jpg",
      "/images/Project_12/samartheducation5.jpg",
      "/images/Project_12/samartheducation6.jpg",
    ],
    challenge:
      "Integrating modern design while maintaining warmth and livability.",
    solution:
      "Used natural materials and created flowing indoor-outdoor spaces.",
    status: "Completed",
  },{
    id: 29,
    title: "Serene Bedroom Redesign",
    slug: "serene-bedroom-redesign",
    image: "/images/interior-resedential/4.jpg",
    category: "Interior design",
    aspectRatio: "4/3",
    description:
      "A cozy and calming bedroom design with warm lighting, soft textures, and a harmonious color palette.",
    shortDescription: "Calm and cozy bedroom redesign.",
    location: "Pune",
    gallery: [
      "/images/interior-resedential/1.jpg",
      "/images/interior-resedential/2.jpg",
      "/images/interior-resedential/3.jpg",
      "/images/interior-resedential/4.jpg",
      "/images/interior-resedential/5.jpg",
      "/images/interior-resedential/6.jpg",
      "/images/interior-resedential/7.jpg",
      "/images/interior-resedential/8.jpg",
      "/images/interior-resedential/9.jpg",
      "/images/interior-resedential/10.jpg",
      "/images/interior-resedential/11.jpg",
      "/images/interior-resedential/12.jpg",
      "/images/interior-resedential/13.jpg",
      "/images/interior-resedential/14.jpg",
      "/images/interior-resedential/15.jpg",
      "/images/interior-resedential/16.jpg",
    ],
    status: "Completed",
  },
  {
    id: 13,
    title: "School Feasibility Study, Pune",
    slug: "school-feasibility-study",
    image: "/images/Project_13/schoolstudy1.JPG",
    category: "Institutes",
    aspectRatio: "16/9",
    description:
      "A modern residential project that pushes the boundaries of contemporary living spaces.",
    shortDescription: "Modern family home with innovative design",
    year: 2019,
    client: "Pune Developer",
    location: "Pune, Maharashtra",
    area: "6,075",
    builtarea: "",
    services: ["Architecture"],
    team: ["Amit Chaubal", "Kaustubh Shevade"],
    gallery: [
      "/images/Project_13/schoolstudy1.JPG",
      "/images/Project_13/schoolstudy2.JPG",
      "/images/Project_13/schoolstudy3.JPG",
      "/images/Project_13/schoolstudy4.JPG",
    ],
    challenge:
      "Integrating modern design while maintaining warmth and livability.",
    solution:
      "Used natural materials and created flowing indoor-outdoor spaces.",
    status: "Unbuilt",
  },
  {
    id: 14,
    title: "School Feasibility Study, Pune",
    slug: "School-Feasibility-Study-Pune",
    image: "/images/Project_14/school1.JPG",
    category: "Institutes",
    aspectRatio: "4/3",
    description:
      "A detailed feasibility study for a proposed school in Pune, focusing on sustainable design and architectural innovation.",
    shortDescription: "Feasibility study for a sustainable school in Pune.",
    year: 2019,
    client: "Pune Developer",
    location: "Pune",
    area: "53,540 sq ft",
    builtarea: "Unbuilt",
    services: ["Feasibility Study", "Architectural Design"],
    team: ["Amit Chaubal", "Kaustubh Shevade"],
    gallery: [
      "/images/Project_14/school1.JPG",
      "/images/Project_14/school2.JPG",
      "/images/Project_14/school3.JPG",
      "/images/Project_14/school4.JPG",
      "/images/Project_14/school5.JPG",
      "/images/Project_14/school6.JPG",
    ],
    challenge:
      "Assessing the feasibility of a large-scale educational institution in Pune.",
    solution:
      "Developed a comprehensive plan focusing on sustainable and cost-effective architecture.",
    status: "Unbuilt",
  },
  {
    id: 15,
    title: "Badminton Academy Feasibility Study, Pune",
    slug: "Badminton-Academy-Feasibility-Study-Pune",
    image: "/images/img8.jpg",
    category: "Commercial",
    aspectRatio: "4/3",
    description:
      "Feasibility study for a state-of-the-art badminton academy in Pune, focusing on sustainable sports infrastructure.",
    shortDescription:
      "Sustainable badminton academy feasibility study in Pune.",
    year: 2018,
    client: "Pune Developer",
    location: "Pune",
    area: "6,075 sq ft",
    builtarea: "Unbuilt",
    services: ["Feasibility Study", "Architectural Design"],
    team: ["Amit Chaubal", "Kaustubh Shevade"],
    gallery: ["/images/img8/detail1.jpg", "/images/img8/detail2.jpg"],
    challenge:
      "Evaluating the feasibility of creating a modern badminton academy with energy-efficient facilities.",
    solution:
      "Proposed an optimized layout with eco-friendly materials and sustainable designs.",
    status: "Unbuilt",
  },
  {
    id: 16,
    title: "Science Research Park, IIT Bombay, Mumbai",
    slug: "Science-Research-Park-IIT-Bombay-Mumbai",
    image: "/images/img9.jpg",
    category: "Institutes",
    aspectRatio: "4/3",
    description:
      "A visionary project to establish a cutting-edge Science Research Park at IIT Bombay, fostering innovation and collaboration.",
    shortDescription:
      "Science Research Park initiative at IIT Bombay for innovation and collaboration.",
    year: 2016,
    client: "IIT Bombay",
    location: "Mumbai",
    area: "Not Specified",
    builtarea: "Unbuilt",
    services: ["Conceptual Design", "Feasibility Study"],
    team: ["Amit Chaubal", "Kaustubh Shevade"],
    gallery: ["/images/img9/detail1.jpg", "/images/img9/detail2.jpg"],
    challenge:
      "Developing a research-oriented park within a bustling academic environment, adhering to space constraints.",
    solution:
      "Proposed a sustainable and innovative design tailored to research needs and academic synergy.",
    status: "Unbuilt",
  },
  {
    id: 17,
    title: "Design College, IIT Bombay, Mumbai",
    slug: "Design-College-IIT-Bombay-Mumbai",
    image: "/images/img10.jpg",
    category: "Institutes",
    aspectRatio: "4/3",
    description:
      "Proposed a creative and functional design for a new design college at IIT Bombay, enhancing student learning and innovation.",
    shortDescription:
      "Design college initiative at IIT Bombay to nurture creativity and innovation.",
    year: 2016,
    client: "IIT Bombay",
    location: "Mumbai",
    area: "Not Specified",
    builtarea: "Unbuilt",
    services: ["Conceptual Design", "Feasibility Study"],
    team: ["Amit Chaubal", "Kaustubh Shevade"],
    gallery: ["/images/img10/detail1.jpg", "/images/img10/detail2.jpg"],
    challenge:
      "Creating a unique identity for the design college while aligning with IIT Bombay's academic culture.",
    solution:
      "Developed a design emphasizing modernity, functionality, and collaborative spaces for students.",
    status: "Unbuilt",
  },
  {
    id: 18,
    title: "ESLBARC, Surat",
    slug: "ESLBARC-Surat",
    image: "/images/img11.jpg",
    category: "Institutes",
    aspectRatio: "4/3",
    description:
      "Proposed design for ESLBARC in Surat, focusing on sustainable architecture and advanced research facilities.",
    shortDescription:
      "Sustainable and functional research facility design for ESLBARC, Surat.",
    year: 2013,
    client: "BARC",
    location: "Surat",
    area: "Not Specified",
    builtarea: "Unbuilt",
    services: ["Conceptual Design", "Feasibility Study"],
    team: ["Amit Chaubal", "Kaustubh Shevade"],
    gallery: ["/images/img11/detail1.jpg", "/images/img11/detail2.jpg"],
    challenge:
      "Integrating sustainable architecture with advanced research requirements.",
    solution:
      "Created a concept blending modern research needs with environmentally conscious design.",
    status: "Unbuilt",
  },
  {
    id: 19,
    title: "Master Plan and Architecture for Sayaji, Kolhapur",
    slug: "master-plan-sayaji-kolhapur",
    image: "/images/img12.jpg",
    category: "Hotel",
    aspectRatio: "4/3",
    description:
      "Comprehensive master plan and architectural design for Sayaji, Kolhapur, blending hospitality needs with sustainable architecture.",
    shortDescription:
      "Master plan and architecture for a hospitality project in Kolhapur.",
    year: 2022,
    client: "DY Patil Hospitality",
    location: "Kolhapur",
    area: "19,910 sqm",
    builtarea: "35,366 sqm",
    services: ["Master Planning", "Architectural Design"],
    team: ["Amit Chaubal", "Kaustubh Shevade"],
    gallery: ["/images/img1/detail1.jpg", "/images/img1/detail2.jpg"],
    challenge:
      "Creating an efficient and aesthetically pleasing hospitality design while adhering to sustainability principles.",
    solution:
      "Developed a competition-winning concept integrating innovative hospitality features with modern architecture.",
    status: "Unbuilt",
  },
  {
    id: 20,
    title: "Façade Design Scheme for Darode Jog, Pune",
    slug: "facade-design-darode-jog",
    image: "/images/img13.jpg",
    category: "Institutes",
    aspectRatio: "4/3",
    description:
      "Façade design scheme for a mixed-use project by Darode Jog in Pune, emphasizing contemporary aesthetics and functionality.",
    shortDescription:
      "Innovative façade design for a mixed-use development in Pune.",
    year: 2014,
    client: "Darode Jog",
    location: "Pune",
    area: "",
    builtarea: "",
    services: ["Façade Design"],
    team: ["Amit Chaubal", "Kaustubh Shevade"],
    gallery: ["/images/img2/detail1.jpg", "/images/img2/detail2.jpg"],
    challenge:
      "Designing a façade that balances aesthetic appeal with the functional needs of a mixed-use development.",
    solution:
      "Crafted a unique façade scheme integrating modern design principles to enhance the building's overall character.",
    status: "Unbuilt",
  },
  {
    id: 21,
    title: "Residential High Rise Elevation Concept, Mumbai",
    slug: "residential-high-rise-elevation-mumbai",
    image: "/images/img14.jpg",
    category: "Residential",
    aspectRatio: "4/3",
    description:
      "Elevation concept for a high-rise residential project in Mumbai, focusing on modern design and urban aesthetics.",
    shortDescription:
      "Innovative elevation concept for a high-rise residential building in Mumbai.",
    year: 2014,
    client: "Mumbai Developer",
    location: "Mumbai",
    area: "",
    builtarea: "",
    services: ["Concept Design"],
    team: ["Amit Chaubal", "Kaustubh Shevade"],
    gallery: ["/images/img3/detail1.jpg", "/images/img3/detail2.jpg"],
    challenge:
      "Creating a modern and visually appealing elevation for a residential high-rise while addressing urban constraints.",
    solution:
      "Designed a contemporary elevation concept that balances form and functionality, enhancing the urban skyline.",
    status: "Unbuilt",
  },
  {
    id: 22,
    title: "Residential High Rise Concept, Pune",
    slug: "residential-high-rise-concept-pune",
    image: "/images/img15.jpg",
    category: "Residential",
    aspectRatio: "4/3",
    description:
      "Concept design for a residential high-rise in Pune, focusing on modern architecture and urban living.",
    shortDescription:
      "Concept design for a modern residential high-rise in Pune.",
    year: 2016,
    client: "Paranjape Schemes, Pune",
    location: "Pune",
    area: "",
    builtarea: "",
    services: ["Concept Design"],
    team: ["Amit Chaubal", "Kaustubh Shevade"],
    gallery: ["/images/img4/detail1.jpg", "/images/img4/detail2.jpg"],
    challenge:
      "Creating a modern residential high-rise concept in a growing urban area, balancing functionality and aesthetics.",
    solution:
      "Developed a concept that emphasizes efficient use of space and modern architectural design, integrating well into Pune's urban landscape.",
    status: "Unbuilt",
  },

  {
    id: 23,
    title: "Married Student Accommodation, IIT Bombay, Mumbai",
    slug: "Married-Student-Accommodation-IIT-Bombay-Mumbai",
    image: "/images/img16.jpg",
    category: "Residential",
    aspectRatio: "",
    description: "",
    shortDescription: "",
    year: 2014,
    client: "IIT Bombay",
    location: "Mumbai",
    area: "",
    builtarea: "",
    services: ["Architecture"],
    team: ["Amit Chaubal", "Kaustubh Shevade"],
    gallery: [],
    challenge: "",
    solution: "",
    status: "Unbuilt",
  },
  {
    id: 24,
    title: "Residential High Rise Concept, Hyderabad",
    slug: "Residential-High-Rise-Concept-Hyderabad",
    image: "/images/img1.jpg",
    category: "Residential",
    aspectRatio: "",
    description: "",
    shortDescription: "",
    year: 2022,
    client: "Hyderabad Developer",
    location: "Hyderabad",
    area: "",
    builtarea: "",
    services: ["Architecture"],
    team: ["Amit Chaubal", "Kaustubh Shevade"],
    gallery: [],
    challenge: "",
    solution: "",
    status: "Unbuilt",
  },
  
  {
    id: 31,
    title: "Elegant Dining Room Makeover",
    slug: "elegant-dining-room-makeover",
    image: "/images/interior-resedential/10.jpg",
    category: "Interior design",
    aspectRatio: "4/3",
    description:
      "A sophisticated dining area featuring luxurious furniture, exquisite lighting, and a touch of elegance.",
    shortDescription: "Sophisticated dining room design.",
    location: "Pune",
    gallery: [
      "/images/interior-resedential/1.jpg",
      "/images/interior-resedential/2.jpg",
      "/images/interior-resedential/3.jpg",
      "/images/interior-resedential/4.jpg",
      "/images/interior-resedential/5.jpg",
      "/images/interior-resedential/6.jpg",
      "/images/interior-resedential/7.jpg",
      "/images/interior-resedential/8.jpg",
      "/images/interior-resedential/9.jpg",
      "/images/interior-resedential/10.jpg",
      "/images/interior-resedential/11.jpg",
      "/images/interior-resedential/12.jpg",
      "/images/interior-resedential/13.jpg",
      "/images/interior-resedential/14.jpg",
      "/images/interior-resedential/15.jpg",
      "/images/interior-resedential/16.jpg",
    ],
    status: "Completed",
  },
  {
    id: 32,
    title: "Creative Studio Workspace",
    slug: "creative-studio-workspace",
    image: "/images/interior-office/4.jpg",
    category: "Interior design",
    aspectRatio: "4/3",
    description:
      "A vibrant and creative studio designed for artists and creators, featuring flexible layouts and inspiring decor.",
    shortDescription: "Flexible and inspiring studio design.",
    location: "Kolkata",
    gallery: [
      "/images/interior-office/1.jpg",
      "/images/interior-office/2.jpg",
      "/images/interior-office/3.jpg",
      "/images/interior-office/4.jpg",
      "/images/interior-office/5.jpg",
      "/images/interior-office/6.jpg",
      "/images/interior-office/7.jpg",
      "/images/interior-office/8.jpg",
      "/images/interior-office/9.jpg",
      "/images/interior-office/10.jpg",
      "/images/interior-office/11.jpg",
      "/images/interior-office/12.jpg",
      "/images/interior-office/13.jpg",
      "/images/interior-office/14.jpg",
      "/images/interior-office/15.jpg",
      "/images/interior-office/16.jpg",
      "/images/interior-office/17.jpg",
      "/images/interior-office/18.jpg",
      "/images/interior-office/19.jpg",
      "/images/interior-office/20.jpg",
      "/images/interior-office/21.jpg",
      "/images/interior-office/22.jpg",
      "/images/interior-office/23.jpg",
      "/images/interior-office/24.jpg",
      "/images/interior-office/25.jpg"
    ],
    status: "Completed",
  },
  {
    id: 33,
    title: "Sustainable Home Design",
    slug: "sustainable-home-design",
    image: "/images/interior-resedential/3.jpg",
    category: "Interior design",
    aspectRatio: "4/3",
    description:
      "An eco-friendly home with sustainable materials, energy-efficient systems, and a green aesthetic.",
    shortDescription: "Eco-friendly and sustainable home design.",
    location: "Goa",
    gallery: [
      "/images/interior-resedential/1.jpg",
      "/images/interior-resedential/2.jpg",
      "/images/interior-resedential/3.jpg",
      "/images/interior-resedential/4.jpg",
      "/images/interior-resedential/5.jpg",
      "/images/interior-resedential/6.jpg",
      "/images/interior-resedential/7.jpg",
      "/images/interior-resedential/8.jpg",
      "/images/interior-resedential/9.jpg",
      "/images/interior-resedential/10.jpg",
      "/images/interior-resedential/11.jpg",
      "/images/interior-resedential/12.jpg",
      "/images/interior-resedential/13.jpg",
      "/images/interior-resedential/14.jpg",
      "/images/interior-resedential/15.jpg",
      "/images/interior-resedential/16.jpg",
    ],
    status: "Completed",
  },

];

// {
//   id: 4,
//   title: "Contemporary Residential Design",
//   slug: "contemporary-residential-design",
//   image: "/images/img4.jpg",
//   category: "Residential",
//   aspectRatio: "16/9",
//   description: "A modern residential project that pushes the boundaries of contemporary living spaces.",
//   shortDescription: "Modern family home with innovative design",
//   year: 2024,
//   client: "Private Client",
//   location: "Seattle, Washington",
//   area: "4,500 sq ft",
//   services: ["Residential Architecture", "Interior Design", "Landscape Planning"],
//   team: ["Maria Garcia - Lead Architect", "Tom Wilson - Landscape Designer"],
//   gallery: ["/images/img4/detail1.jpg", "/images/img4/detail2.jpg"],
//   challenge: "Integrating modern design while maintaining warmth and livability.",
//   solution: "Used natural materials and created flowing indoor-outdoor spaces.",
//   status: "Completed"
// },
// {
//   id: 5,
//   title: "Boutique Hotel Suite",
//   slug: "boutique-hotel-suite",
//   image: "/images/img5.jpg",
//   category: "Hotel",
//   aspectRatio: "9/16",
//   description: "Luxurious boutique hotel suites that offer unique experiences through design.",
//   shortDescription: "Unique boutique hotel experience",
//   year: 2023,
//   client: "Boutique Stays Inc.",
//   location: "Portland, Oregon",
//   area: "12,000 sq ft",
//   services: ["Hotel Design", "Interior Styling", "Custom Furniture"],
//   team: ["Sophie Wright - Interior Designer", "James Lee - Furniture Designer"],
//   gallery: ["/images/img5/detail1.jpg", "/images/img5/detail2.jpg"],
//   challenge: "Creating unique identities for each suite while maintaining brand coherence.",
//   solution: "Developed a modular design system with customizable elements.",
//   status: "Completed"
// },
// {
//   id: 6,
//   title: "Corporate Office Design",
//   slug: "corporate-office-design",
//   image: "/images/img6.jpg",
//   category: "Commercial",
//   aspectRatio: "4/5",
//   description: "A forward-thinking corporate office space that promotes collaboration and productivity.",
//   shortDescription: "Modern corporate office with collaborative spaces",
//   year: 2024,
//   client: "Tech Innovations Corp",
//   location: "San Francisco, California",
//   area: "30,000 sq ft",
//   services: ["Office Planning", "Interior Design", "Workplace Strategy"],
//   team: ["Robert Chang - Lead Designer", "Anna Kim - Workplace Strategist"],
//   gallery: ["/images/img6/detail1.jpg", "/images/img6/detail2.jpg"],
//   challenge: "Balancing open collaboration spaces with focused work areas.",
//   solution: "Created flexible zones with acoustic treatments and mobile furniture.",
//   status: "Completed"
// },
// {
//   id: 7,
//   title: "Campus Library",
//   slug: "campus-library",
//   image: "/images/img7.jpg",
//   category: "Institutes",
//   aspectRatio: "3/4",
//   description: "A modern library that combines traditional learning spaces with digital integration.",
//   shortDescription: "Modern campus library with integrated technology",
//   year: 2023,
//   client: "City University",
//   location: "Chicago, Illinois",
//   area: "40,000 sq ft",
//   services: ["Educational Design", "Digital Integration", "Interior Planning"],
//   team: ["Michael Brown - Education Specialist", "Sarah Lee - Technology Integration"],
//   gallery: ["/images/img7/detail1.jpg", "/images/img7/detail2.jpg"],
//   challenge: "Integrating modern technology while preserving traditional library functions.",
//   solution: "Created flexible learning spaces with integrated digital resources.",
//   status: "Completed"
// },
// {
//   id: 8,
//   title: "Suburban Family Home",
//   slug: "suburban-family-home",
//   image: "/images/img8.jpg",
//   category: "Residential",
//   aspectRatio: "1/1",
//   description: "A family-oriented suburban home that combines comfort with modern design principles.",
//   shortDescription: "Contemporary suburban family residence",
//   year: 2024,
//   client: "Private Client",
//   location: "Austin, Texas",
//   area: "3,800 sq ft",
//   services: ["Residential Architecture", "Interior Design", "Landscape Design"],
//   team: ["Jennifer White - Residential Architect", "Paul Green - Landscape Architect"],
//   gallery: ["/images/img8/detail1.jpg", "/images/img8/detail2.jpg"],
//   challenge: "Creating a modern family home that maintains warmth and functionality.",
//   solution: "Implemented open-plan living with defined private spaces.",
//   status: "Completed"
// },
// {
//   id: 9,
//   title: "Luxury Spa Hotel",
//   slug: "luxury-spa-hotel",
//   image: "/images/img9.jpg",
//   category: "Hotel",
//   aspectRatio: "16/9",
//   description: "A luxury spa hotel that creates an immersive wellness experience through design.",
//   shortDescription: "Luxury wellness hotel and spa",
//   year: 2023,
//   client: "Wellness Resorts International",
//   location: "Scottsdale, Arizona",
//   area: "45,000 sq ft",
//   services: ["Hotel Architecture", "Spa Design", "Wellness Planning"],
//   team: ["Diana Martinez - Wellness Designer", "John Baker - Hotel Specialist"],
//   gallery: ["/images/img9/detail1.jpg", "/images/img9/detail2.jpg"],
//   challenge: "Creating a serene environment while maintaining operational efficiency.",
//   solution: "Designed flowing spaces with hidden service areas.",
//   status: "Completed"
// },
// {
//   id: 10,
//   title: "Downtown Commercial Plaza",
//   slug: "downtown-commercial-plaza",
//   image: "/images/img10.jpg",
//   category: "Commercial",
//   aspectRatio: "9/16",
//   description: "A mixed-use commercial plaza that revitalizes downtown urban space.",
//   shortDescription: "Urban mixed-use commercial development",
//   year: 2024,
//   client: "Urban Development Corp",
//   location: "Denver, Colorado",
//   area: "80,000 sq ft",
//   services: ["Urban Planning", "Commercial Architecture", "Landscape Design"],
//   team: ["Carlos Rodriguez - Urban Planner", "Emma Thompson - Commercial Architect"],
//   gallery: ["/images/img10/detail1.jpg", "/images/img10/detail2.jpg"],
//   challenge: "Integrating multiple uses while maintaining urban context.",
//   solution: "Created distinct zones connected by public spaces.",
//   status: "In Progress"
// },
// {
//   id: 11,
//   title: "Residential Villa",
//   slug: "residential-villa",
//   image: "/images/img11.jpg",
//   category: "Residential",
//   aspectRatio: "4/5",
//   description: "A luxury residential villa that combines traditional elements with modern living.",
//   shortDescription: "Luxury villa with modern amenities",
//   year: 2023,
//   client: "Private Client",
//   location: "Palm Beach, Florida",
//   area: "6,500 sq ft",
//   services: ["Luxury Residential", "Interior Design", "Landscape Architecture"],
//   team: ["Alexandra Foster - Villa Specialist", "Richard Gray - Landscape Designer"],
//   gallery: ["/images/img11/detail1.jpg", "/images/img11/detail2.jpg"],
//   challenge: "Balancing luxury with practical family living spaces.",
//   solution: "Created distinct private and entertainment zones.",
//   status: "Completed"
// },
// {
//   id: 12,
//   title: "University Science Wing",
//   slug: "university-science-wing",
//   image: "/images/img12.jpg",
//   category: "Institutes",
//   aspectRatio: "3/4",
//   description: "A state-of-the-art science facility designed for modern research and education.",
//   shortDescription: "Modern university research facility",
//   year: 2024,
//   client: "State University System",
//   location: "Ann Arbor, Michigan",
//   area: "60,000 sq ft",
//   services: ["Educational Architecture", "Laboratory Design", "Sustainability"],
//   team: ["Dr. William Chen - Lab Specialist", "Laura Martinez - Education Architect"],
//   gallery: ["/images/img12/detail1.jpg", "/images/img12/detail2.jpg"],
//   challenge: "Creating flexible research spaces with advanced safety features.",
//   solution: "Implemented modular lab designs with smart safety systems.",
//   status: "Completed"
// },
// {
//   id: 13,
//   title: "Luxury Resort Hotel",
//   slug: "luxury-resort-hotel",
//   image: "/images/img13.jpg",
//   category: "Hotel",
//   aspectRatio: "1/1",
//   description: "An exclusive resort hotel that creates unique guest experiences through architecture.",
//   shortDescription: "Exclusive luxury resort destination",
//   year: 2023,
//   client: "Global Resorts Ltd",
//   location: "Maui, Hawaii",
//   area: "120,000 sq ft",
//   services: ["Resort Architecture", "Interior Design", "Landscape Planning"],
//   team: ["Michelle Wong - Resort Specialist", "David Turner - Landscape Architect"],
//   gallery: ["/images/img13/detail1.jpg", "/images/img13/detail2.jpg"],
//   challenge: "Integrating luxury amenities while preserving natural environment.",
//   solution: "Created eco-friendly design with minimal environmental impact.",
//   status: "Completed"
// },
// {
//   id: 14,
//   title: "High-End Commercial Complex",
//   slug: "high-end-commercial-complex",
//   image: "/images/img14.jpg",
//   category: "Commercial",
//   aspectRatio: "16/9",
//   description: "A premium commercial complex that sets new standards in retail architecture.",
//   shortDescription: "Premium retail and office complex",
//   year: 2024,
//   client: "Luxury Retail Developments",
//   location: "Las Vegas, Nevada",
//   area: "90,000 sq ft",
//   services: ["Retail Architecture", "Commercial Planning", "Lighting Design"],
//   team: ["Kevin Park - Retail Specialist", "Rachel Adams - Lighting Designer"],
//   gallery: ["/images/img14/detail1.jpg", "/images/img14/detail2.jpg"],
//   challenge: "Creating distinctive retail spaces while maintaining flow.",
//   solution: "Developed unique storefronts with cohesive public areas.",
//   status: "In Progress"
// },
// {
//   id: 15,
//   title: "Modern Apartment Complex",
//   slug: "modern-apartment-complex",
//   image: "/images/img15.jpg",
//   category: "Residential",
//   aspectRatio: "9/16",
//   description: "A contemporary apartment complex that redefines urban living standards.",
//   shortDescription: "Contemporary urban living spaces",
//   year: 2023,
//   client: "Urban Living Developers",
//   location: "Nashville, Tennessee",
//   area: "150,000 sq ft",
//   services: ["Multi-family Architecture", "Urban Planning", "Interior Design"],
//   team: ["Steven Lee - Housing Specialist", "Amanda White - Urban Designer"],
//   gallery: ["/images/img15/detail1.jpg", "/images/img15/detail2.jpg"],
//   challenge: "Maximizing living space while creating community areas.",
//   solution: "Designed efficient units with shared amenities.",
//   status: "Completed"
// },
// {
//   id: 16,
//   title: "Community College Campus",
//   slug: "community-college-campus",
//   image: "/images/img16.jpg",
//   category: "Institutes",
//   aspectRatio: "4/5",
//   description: "A modern community college campus designed to foster learning and community engagement.",
//   shortDescription: "Modern educational campus design",
//   year: 2024,
//   client: "State Community College",
//   location: "Sacramento, California",
//   area: "200,000 sq ft",
//   services: ["Campus Planning", "Educational Architecture", "Landscape Design"],
//   team: ["Steven Lee - Housing Specialist", "Amanda White - Urban Designer"],
//   gallery: ["/images/img15/detail1.jpg", "/images/img15/detail2.jpg"],
//   challenge: "Maximizing living space while creating community areas.",
//   solution: "Designed efficient units with shared amenities.",
//   status: "Completed"
// },
